platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../../capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../capacitor/ios'
  pod 'CapacitorClipboard', :path => '../../../capacitor-plugins/clipboard'
  pod 'CapacitorHaptics', :path => '../../../capacitor-plugins/haptics'
  pod 'CapacitorScreenReader', :path => '../../../capacitor-plugins/screen-reader'
  pod 'CapacitorStorage', :path => '../../../capacitor-plugins/storage'
  pod 'CapacitorTextZoom', :path => '../../../capacitor-plugins/text-zoom'
  # Do not delete
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end
